# Generated by Django 3.1.2 on 2020-10-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaronaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('population', models.CharField(blank=True, max_length=250, null=True)),
                ('cases', models.CharField(blank=True, max_length=250, null=True)),
                ('deaths', models.CharField(blank=True, max_length=250, null=True)),
                ('day', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.CharField(blank=True, max_length=250, null=True)),
                ('current_time', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
